### ISSUE TITLE
Using Iphone images as input data

### ISSUE THREAD

**Issue by ForMyCat** [Wanggcong/SparseNeRF#14]
If I want to use RGB images taken from Iphone as input data (no depth info), should I copy datasets_depth_iphone.py to create the datasets_depth_xyz.py? Or should I just use the original datasets_depth_iphone.py and nvs_rgbd_iphone.gin?

**Comment by ForMyCat** [comment]
Or can you briefly explain the pipeline for data preping if I want to use only RGB images as input?

**Comment by Wanggcong** [comment]
Thank you for you question.
If you do not use depth info, you can directly use [train_llff_dtu.py](https://github.com/Wanggcong/SparseNeRF/blob/main/train_llff_dtu.py) like llff dataset.

More precisely, I do not know the question "if I want to use only RGB images as input". In our paper, if you do not have depth maps from depth sensors, you can use depth estimation to predict depth maps.

Moreover, different scripts about datasets_depth_xxx.py are very similar. We separate the scripts because Kinnect has some noises in depth maps,  and some uses inverse depth maps while some use disparity maps.

**Comment by Wanggcong** [comment]
Basically, you can prepare your data as follows:
1) Capture a few RGB images. Prepare your dataset like the iPhone dataset, for example, training images are named with '_train.jpg', test images are named with '_test.jpg'

2) Calculate camera poses by COLMAP

3) Calcuate inverse depth maps by the DPT depth estimator.

4) Organize datasets as the iPhone dataset (the depth map provided by iPhone are also inverse depth maps).

5) Set variable in iphone.gin, and use datasets_depth_iphone.py and train_iphone.py

**Comment by Wanggcong** [comment]
Do you have any questions about this issue?

**Comment by Wanggcong** [comment]
I closed this issue since there is no further question. You might re-open the issue and open a new issue.
