### ISSUE TITLE
tensorflow/stream_executor/platform/default/dso_loade r.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so. 11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: / usr/local/cuda/lib

### ISSUE THREAD

**Issue by kafei123456** [Wanggcong/SparseNeRF#18]
The CUDA version is not CUDA10.1 ？How to deal with this problem？

**Comment by Wanggcong** [comment]
Thanks. I think you might not install cuda 10.1 successfully. Please try some tutorials about cuda installation.

**Comment by Wanggcong** [comment]
Since there are no further questions, I closed the issue. You might re-open it if necessary.

**Comment by SipingLiu0** [comment]
@Wanggcong
I have encountered the same problem, could you give me some advice on how to solve this problem?
tensorflow 2.6.2 is given in the requirements.txt file, but according to the official tensorflow website, it requires cuda 11.2 instead of 10.1. 
I tried to downgrade tensorflow version to 2.3.0, but it will not be compatible to oryx.

**Comment by Star-XingHe** [comment]
I use CUDA 10.1, but still encounter the same problem.
