### ISSUE TITLE
Depth scales in NVS-RGBG Datasets

### ISSUE THREAD

**Issue by skyir0n** [Wanggcong/SparseNeRF#19]
Depth maps provided in the dataset are written as a form of 'png' file and their values are 16-bit.
Here are my question. Are the values real scale? Although I've tried to backproject the a few of images to 3D world coordinates by using the images, depth maps, and the camera poses, but the points at each viewpoint are not aligned each other. I think that the depth values lost the information of the real world due to the normalization. Could you provide the real-scaled depth maps?

**Comment by Wanggcong** [comment]
Most of the existing monocular depth estimation models provide depth maps with a scale and a bias. It is impossible to get the real scaled depth maps for these models. Let me show some examples. On the [DTU dataset](https://roboimagedata.compute.dtu.dk/?page_id=36), there are some toy buildings. But if you do not know they are toys, the scale would be very large. For COLMAP (used for camera pose estimation), it also loses the scale. 

Actually, in many cases, we are only interested in the shape instead of the scale in 3D reconstruction.

**Comment by Wanggcong** [comment]
Since there are no further questions, I closed the issue. You might re-open it if necessary.
