### ISSUE TITLE
code release and the details about `L_{rank}`

### ISSUE THREAD

**Issue by elenacliu** [Wanggcong/SparseNeRF#4]
I'd like to know how you use inverse depth because nerf just outputs non-inverse depth? So you take the reciprocal of the depth calculated by nerf?

**Comment by Wanggcong** [comment]
Thank you for your question. Since we use depth ranking, we do not need to transform the inverse depth to the standard depth. This is super convenient. By the way, we are working hard on the code release (re-running and double-checking).

**Comment by elenacliu** [comment]
thx for your quick reply! But to the best of my knowledge, nerf's computation of depth is non-inverse depth.

<img width="484" alt="image" src="https://github.com/Wanggcong/SparseNeRF/assets/44845151/72c7e9d9-9e7b-4414-a573-540ad8aba544">

so to ensure the consistency of inverse depth output by DPT and the non-inverse depth output by nerf, I guess you need to convert nerf's depth into inverse depth first.

**Comment by elenacliu** [comment]
oh sorry, I checked your paper again, does the $d_{dpt}^{k_1}$ mean the `rank` instead of the value of inverse depth?

<img width="476" alt="image" src="https://github.com/Wanggcong/SparseNeRF/assets/44845151/c3db99f8-1489-4789-a4de-b3ee9cc63373">

**Comment by Wanggcong** [comment]
> oh sorry, I checked your paper again, does the ddptk1 mean the `rank` instead of the value of inverse depth?
> 
> <img alt="image" width="476" src="https://user-images.githubusercontent.com/44845151/258655984-c3db99f8-1489-4789-a4de-b3ee9cc63373.png">

Not really. The d_{dpt}^{k1} denotes the value of the inverse depth. Let me give an example. If two sampling points d_{dpt}^{k1} and d_{dpt}^{k2} from a depth map satifies  d_{dpt}^{k1}<=d_{dpt}^{k2}, we then compute the loss from the corresponding points in the rendered depth map d_r by max(d_{r}^{k1}, d_{r}^{k1}+m,0). Note that if you use the inverse depth map as d_{dpt}, then it should be d_{dpt}^{k1}>=d_{dpt}^{k2}. You might find it we only use the depth ranking (d_{dpt}^{k1}<=d_{dpt}^{k2}) instead of absolute depth values. That is, scaling  d_{dpt} or any transformation of  d_{dpt} does not affect the loss. We just care about the ranking.

Does we need to transform the depth map of nerf's output into the inverse map? No. The loss max(d_{r}^{k1}, d_{r}^{k1}+m,0) can be directly computed in the depth map of nerf's output.

Please let me know if I make this clear.

**Comment by elenacliu** [comment]
Thank you for your clear explanation!

**Comment by Wanggcong** [comment]
Code is released. Please check it. If you have any questions, you can re-open it or open a new issue.

**Comment by elenacliu** [comment]
Hello, your code regularizes the depth using midas depth output, and midas depth output is inverse relative depth.
if I want to train with my own data using midas depth, can I run your code directly?
and if I want to train with my own data using ground truth depth, should I modify the code?

**Comment by Wanggcong** [comment]
> Hello, your code regularizes the depth using midas depth output, and midas depth output is inverse relative depth. if I want to train with my own data using midas depth, can I run your code directly? and if I want to train with my own data using ground truth depth, should I modify the code?

Thank you your question. I will release a feature (a tutorial) that explain how to use our code for the custom dataset in a few coming days. I will let you know when I did it. Please give me a few days.

**Comment by Wanggcong** [comment]
> Hello, your code regularizes the depth using midas depth output, and midas depth output is inverse relative depth. if I want to train with my own data using midas depth, can I run your code directly? and if I want to train with my own data using ground truth depth, should I modify the code?

Hi, I write a rough tutorial in this [link](https://github.com/Wanggcong/SparseNeRF/blob/main/tutorial.md). Please let me know if it can solve your problem.

**Comment by elenacliu** [comment]
thank you! it really helps
