### ISSUE TITLE
why are the multipliers of depth continuity loss of LLFF and DTU dataset different?

### ISSUE THREAD

**Issue by hermosaaurora** [Wanggcong/SparseNeRF#8]
https://github.com/Wanggcong/SparseNeRF/blob/111c17d9fb7f4285eb8c473e0b5e5fe69b19705b/train_llff_dtu.py#L135-L140

For LLFF, it is 0.01
While for DTU, it is 1

I'm just wondering why they have two orders of magnitude difference. And if we use our own dataset how to choose the multiplier?

**Comment by Wanggcong** [comment]
Thank you. The reason is that on LLFF, the field of views are very limited. On DTU, the field of views are large. The continuity loss is not that obvious. Note that the continuity loss mainly improve the visual quality (fewer floaters). It could not improve some metrics like PSNR and SSIM in some cases, especifically for the limited field of views. This is also observed in Table 2 of [MipNeRF-360](https://arxiv.org/pdf/2111.12077.pdf).

**Comment by hermosaaurora** [comment]
thx!
